SURVEYS_KEY = 'surveys'
ADMINS_KEY = 'admins'
SURVEY_TITLE_KEY = 'survey_title'
SURVEY_DESCRIPTION_KEY = 'survey_description'
SURVEYS_NONE = 'Опросов пока что нет! Создайте новый опрос, нажав на кнопку выше'
SURVEYS_MANAGE_BUTTON = 'Управление опросами'
SURVEYS_MANAGE = 'manage'
START_ARGLESS = 'Команда зарезервирована для управления опросами через результаты поиска. Используйте /start manage'