(START_STATE, START_SURVEY_STATE, PICK_SURVEY_STATE, MAIN_MENU_STATE, 
	LANG_STATE) = range(5)
(GET_TITLE_STATE, SAVE_TITLE_STATE, GET_DESC_STATE, SAVE_DESC_STATE, 
	GET_QUESTION_STATE, SAVE_QUESTION_STATE, GET_MULTIANS_STATE, RECORD_MULTIANS_STATE, 
	SAVE_MULTIANS_STATE, GET_ANSWER_STATE, RECORD_ANSWER_STATE, SAVE_ANSWER_STATE, 
	REVIEW_STATE, END, START_OVER_STATE) = range(5, 20)
(PICK_PART_STATE, EDIT_TITLE_STATE, EDIT_DESC_STATE, PICK_QUESTION_STATE, 
	PICK_QUESTION_PART_STATE, EDIT_QUESTION_TEXT_STATE, END_COMPOSE, END_MANAGE,
	EDIT_MULTI_STATE, EDIT_ANSWERS_STATE, PICK_ANSWER_STATE, EDIT_ANSWER_STATE,
    REMOVE_ANSWER_CONFIRM_STATE) = range(20, 33)
(PICK_SURVEY_STATE) = range(33, 34)
(MANAGE_SURVEYS_STATE, MANAGE_PICK_SURVEY_STATE, MANAGE_SURVEY_STATE, MANAGE_DELETE_CONFIRM_STATE,
    MANAGE_AFTER_DELETE_STATE) = range(34, 39)
(PICK_SETTING_STATE, SETTINGS_LANG_STATE) = range(39, 41)


CHOOSE_LANG = '🇷🇺: Русский\n🇺🇸: English'
RU_CB = 'RU'
EN_CB = 'EN'

START_SURVEY_CB = 'START_SURVEY'
MANAGE_SURVEYS_CB = 'MANAGE_SURVEYS'
SETTINGS_CB = 'SETTINGS'
SETTINGS_LANG_CB = 'SETTINGS_LANG'
CREATE_SURVEY_CB = 'CREATE_SURVEY'
CHOOSE_SURVEY_CB = 'CHOOSE_SURVEY'
SAVE_TITLE_CB = 'SAVE_TITLE'
SAVE_DESC_CB = 'SAVE_DESC'
SAVE_QUESTION_CB = 'SAVE_QUESTION'
SAVE_MULTI_CB = 'SAVE_MULTI'
SAVE_ANSWER_CB = 'SAVE_ANSWER'
NEXT_ANSWER_CB = 'NEXT_ANSWER'
NEXT_QUESTION_CB = 'NEXT_QUESTION'
FINISH_CREATING_CB = 'FINISH_CREATING'
CREATION_COMPLETE_CB = 'CREATION_COMPLETE'
EDIT_SURVEY_COMPOSE_CB = 'EDIT_SURVEY_COMPOSE'
EDIT_SURVEY_MANAGE_CB = 'EDIT_SURVEY_MANAGE'
START_OVER_SURVEY_CB = 'START_OVER_SURVEY'
ENTER_AGAIN_CB = 'ENTER_AGAIN'
PICK_SURVEY_CB = 'PICK_SURVEY'
EDIT_TITLE_CB = 'EDIT_TITLE'
EDIT_DESC_CB = 'EDIT_DESC'
EDIT_QUESTIONS_CB = 'EDIT_QUESTIONS'
SAVE_AND_EXIT_CB = 'SAVE_AND_EXIT'
NEW_TITLE_CB = 'NEW_TITLE'
NEW_DESC_CB = 'NEW_DESC'
EDIT_QUESTION_TEXT_CB = 'EDIT_QUESTION_TEXT'
EDIT_MULTI_CB = 'EDIT_MULTI'
EDIT_ANSWERS_CB = 'EDIT_ANSWER'
NEW_QUESTION_TEXT_CB = 'NEW_QUESTION_TEXT'
NEW_MULTI_CB = 'NEW_MULTI'
NEW_ANSWERS_CB = 'NEW_ANSWERS'
KEEP_CURRENT_QUESTION_TEXT_CB = 'KEEP_CURRENT_QUESTION_TEXT'
KEEP_CURRENT_MULTI_CB = 'KEEP_CURRENT_MULTI'
KEEP_CURRENT_ANSWERS_CB = 'KEEP_CURRENT_ANSWERS'
KEEP_CURRENT_TITLE_CB = 'KEEP_CURRENT_TITLE'
KEEP_CURRENT_DESC_CB = 'KEEP_CURRENT_DESC'
EDIT_EXISTING_ANSWER_CB = 'EDIT_EXISTING_ANSWER'
ADD_NEW_ANSWER_CB = 'ADD_NEW_ANSWER'
EDIT_ANSWER_CB = 'EDIT_ANSWER'
REMOVE_ANSWER_CB = 'REMOVE_ANSWER'
RETURN_CB = 'RETURN'
RETURN_START_OVER_CB = 'RETURN_RESTART'
RETURN_TO_MAIN_CB = 'RETURN_TO_MAIN'
MANAGE_DELETE_SURVEY_CB = 'MANAGE_DELETE_SURVEY'
YES_CB = 'YES'
NO_CB = 'NO'